pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/Israelraj626/Project_J'
            }
        }

        stage('Build') {
            steps {
                echo "Nothing to build in this simple project"
            }
        }

        stage('Test') {
            steps {
                sh 'bash tests/test.sh'
            }
        }

        stage('Archive') {
            steps {
                archiveArtifacts artifacts: '**/*.sh', fingerprint: true
            }
        }
    }

    post {
        success {
            echo "Pipeline completed successfully."
        }
        failure {
            echo "Pipeline failed."
        }
    }
}
